version: "2.0.0"

provider:
  type: "local"

ai:
  providers:
    - name: "openai"
      enabled: true
    - name: "google"
      enabled: true
    - name: "anthropic"
      enabled: false
  default_provider: "openai"
  enable_token_tracking: true
  max_tokens_per_request: 8000
  default_temperature: 0.5
  default_model: "gpt-4"

features:
  scaffolding_mode: false
  autonomous_mode: false

tools:
  create_spec:
    enabled: true
    description: "Create technical specification from PRD"
  
  create_tasks_from_spec:
    enabled: true
    description: "Break down engineering spec into actionable tasks"
  
  plan_task:
    enabled: true
    description: "Create detailed execution plan for a task"
    
  implement_task:
    enabled: true
    description: "Execute the planned implementation"
    
  review_task:
    enabled: true
    description: "Perform code review"
    
  test_task:
    enabled: true
    description: "Run and validate tests"
    
  finalize_task:
    enabled: true
    description: "Create commit and pull request"

workflow:
  require_human_approval: true
  enable_ai_review: true
  max_thinking_time: 300
  auto_create_branches: true

providers:
  jira:
    transition_on_start: true
    transition_on_complete: true
    
  linear:
    update_status: true
    
  local:
    task_file_pattern: "*.md"

debug:
  save_debug_logs: true
  save_state_snapshots: true
  log_level: INFO